### ISSUE TITLE
[BPASS] Model_IMF, Mixed_IMF, Mixed_Age

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#43]
What does Model_IMF and Mixed_IMF signify in the BPASS-Input file?  What does mixed IMF signify physically?
I am referring to Model_IMF and Mixed_IMF as referred to in the cmd,py file.

**Comment by HeloiseS** [comment]
Hello RyotaInagaki1!

Thank you for your question.
The Model_IMF and Mixed_IMF are sort of like quantities in a recipe: They tell us how much of each ingredient (stellar model) we want to put in our dish (Universe). The model_imf is the total amount we need to make our universe. the Mixed_IMF is non-zero it tells you that some of that quantity will have to be added later-on in the recipe after the star has been rejuvinated. Sometimes the model_imf equals the mixed_imf because this type of stellar model *only occurs* after rejuvination!

I hope this clarifies  things, but to be fair you shouldn't worry too much about these if you're using them with the CMD object as it will take care of the details for you.

Cheers,
Heloise

**Comment by RyotaInagaki1** [comment]
In this case, the IMF's should be considered as the number of stellar systems of a certain kind, correct? 
I am asking this since I am trying to find a way to incorporate BPASS data to another stellar population synthesis tool called SPISEA (Hosek et. al 2020).
Another thing I want to be extra sure of is whether I should account for the mixed age when creating an isochrone for binary models using BPASS or whether I should simply inspect the stellar model files and just use the ages of the star given there. It may seem trivial of a question to ask, but I just want to make sure that I am using the data correctly.

**Comment by HeloiseS** [comment]
You can't really have isochrones for binary evolution models - not like the single star models at least: there isn't a single track with age it's more scattered and cloudlike. You can just use HRDs and CMDs out of the box :)

**Comment by RyotaInagaki1** [comment]
But in any case, the mixed_age in the code is really the correction factor for the ages of the star that comes from rejuvination?

**Comment by HeloiseS** [comment]
I wouldn't call it a correction factor - it just tells you how much of that model to put in when rejuvination has occured at time t  :)

**Comment by HeloiseS** [comment]
I'm going to close the issue now - feel free to reopen it if needed or ask another question later on :)
