### ISSUE TITLE
[FEATURE] BPASS colour-magnitude diagrams with more filters

### ISSUE THREAD

**Issue by sunnc** [HeloiseS/hoki#48]
It is very exciting to see the new HOKI version which provides colour-magnitude diagrams, which are very useful for observational astronomers.

However, many people may depend on different filters that have not yet been incorporated by the current BPASS version.

I know it requires a larger amount of effort to calculate synthetic magnitudes for more filter systems.

Is there a way that allows the users to calculate synthetic magnitudes manually with their own filter response curves? Will you consider this in future BPASS and HOKI versions?

**Comment by maxbriel** [comment]
Hi sunnc! 

Great to hear you're exciting about `hoki` and its usefulness! 

For the inclusion of magnitude calculations for the stellar models, @HeloiseS might be able to provide more information. 

For synthetic magnitude calculation of stellar populations, we have done some exploratory work. The [spectra branch](https://github.com/HeloiseS/hoki/tree/spectra) contains an extremely basic implementation of magnitude calculations using [pysynphot's](https://pysynphot.readthedocs.io/en/latest/) and custom filter response curves.
I must caution that we do not provide any documentation, tutorial, or support for this branch. Moreover, it is based on an old release of `hoki` and might contain bugs and definitely misses new functionality. I will pick this back up in the future. 

If you want it implemented sooner rather than later, you're welcome to contribute!

**Comment by HeloiseS** [comment]
Hi Ning-Chen, 

What max described works for the spectrum of the whole population but for individual stars we don't have that.
BPASS is in continuous development and we are working on new filters (including Gaia) - for more information on this specific topic you should contact A. Prof Jan Eldridge directly:  j.eldridge@auckland.ac.nz
