### ISSUE TITLE
[BPASS]

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#50]
In the Stellar Models' Binary models directory, there is a subdirectory for binary models and secondary models. Is the directory for binary models the one whose M1 value is the mass of the primary star? 
In the stellar evolution models, how can the compact object of the star or primary or secondary be discerned?
Also, is the second column of the BPASS Stellar input the total mass of the stellar system, the current mass of the primary star, or is it the initial mass of the star?

**Comment by HeloiseS** [comment]
1) yes
2) BPASS stellar evolution stops at CO core because it is enough to determine the remnant - however another piece of software/further analysis is required. TUI is able to take BPASS models and retrieve NS or BH remnants for more details contact j.eldridge@auckland.ac.nz 
3) What do you mean by BPASS Stellar input, do you mean the input files?

**Comment by RyotaInagaki1** [comment]
1. I should have rephrased question 1 a bit more clearly as follows: Is the NEWSEC mods for the secondary star models whose primaries have become compact remnants or are "deceased"?
3. I meant the input files when I mentioned BPASS Stellar input.

**Comment by HeloiseS** [comment]
1. yes pretty much
2. I still don't know specifically what you're talking about - can you give me a file name example?

**Comment by HeloiseS** [comment]
It's been 14 days so I'm going to close the issue - reopen it if you need any more info?
