### ISSUE TITLE
[BPASS] Initial mass of NEWSEC models and Binary QHE Models

### ISSUE THREAD

**Issue by RyotaInagaki1** [HeloiseS/hoki#63]
How do I find the initial masses and separation of the primary star and the secondary star in the NEWSEC models and for the binary QHE models? Should I look at the filenames for indications of the primary mass and the secondary mass or should I look at row in the model grid corresponding to age=0 years?
Also, are all binary QHE models listed in metallicities of <metallicity>hmg?
Thank You,
Ryota Inagaki

**Comment by HeloiseS** [comment]
there should be no discrepancy btw the file names and age 0 - i would personally look at the latter because i can just call the columns for M1 and M2 :) 

what do you mean by metallicities of hmg? the QHE metallicities are the same as the other BPASS models and the are in fractions of metal (Z) z020 : Z = .020 which is solar metallicity (roughly).

**Comment by RyotaInagaki1** [comment]
Please pardon me for some of my unclear wording. Please let me clarify.
For the first question I wanted to find the initial masses of the primary and secondary (by that I mean something along the lines of zero age main sequence or pre-main sequence).
As for the second question, I am wondering if all of the binary QHE models will be in the subdirectory for metallicity that have a suffix "hmg"
